// The Region's seed data: the Institutions and Contacts the CRM starts from, and the researched
// competitor product data. Loaded before the page's script; it only defines data.
// scripts/extract-crm-data.js reads this file too, so keep each list a plain literal.

const SEED_INSTITUTIONS = [
  {id:'kuleuven',name:'KU Leuven',short:'KU Leuven',type:'university',city:'Leuven',website:'https://www.kuleuven.be',founded:1425,description:'The oldest Catholic university in the world still in existence and Belgium\'s largest university, spanning nearly every academic discipline across fifteen faculties.',researchDirector:'Severine Vermeire',libraryDirector:'Hilde Van Kiel'},
  {id:'ugent',name:'Ghent University',short:'UGent',type:'university',city:'Ghent',website:'https://www.ugent.be',founded:1817,description:'One of Belgium\'s leading research universities, established by royal decree and now home to eleven faculties and a strong international research profile.',researchDirector:'Petra De Sutter',libraryDirector:'Rosemie Callewaert'},
  {id:'uantwerpen',name:'University of Antwerp',short:'UAntwerpen',type:'university',city:'Antwerp',website:'https://www.uantwerpen.be',founded:1971,description:'Formed through the merger of three existing Antwerp institutions, with particular strength in tropical medicine, law and the social sciences.',researchDirector:'Herwig Leirs',libraryDirector:'Rik Van Daele'},
  {id:'vub',name:'Vrije Universiteit Brussel',short:'VUB',type:'university',city:'Brussels',website:'https://www.vub.be',founded:1970,description:'The Dutch-speaking university that split from the Université libre de Bruxelles along linguistic lines, known for its international outlook.',researchDirector:'Jan Danckaert',libraryDirector:'Peter Verbist'},
  {id:'uhasselt',name:'Hasselt University',short:'UHasselt',type:'university',city:'Hasselt',website:'https://www.uhasselt.be',founded:1973,description:'The youngest full university in Flanders, with particular strength in mobility, materials and biomedical research.',researchDirector:'Bernard Vanheusden',libraryDirector:'Pieter Lernout'},
  {id:'uclouvain',name:'UCLouvain',short:'UCLouvain',type:'university',city:'Louvain-la-Neuve',website:'https://uclouvain.be',founded:1425,description:'The French-speaking university that split from KU Leuven in 1968, relocating most faculties to the purpose-built town of Louvain-la-Neuve.',researchDirector:'Françoise Smets',libraryDirector:'Muriel Baguet'},
  {id:'uliege',name:'Université de Liège',short:'ULiège',type:'university',city:'Liège',website:'https://www.uliege.be',founded:1817,description:'A public research university spanning Liège\'s Sart Tilman and city-centre campuses, with strengths in engineering, space science and veterinary medicine.',researchDirector:'Anne-Sophie Nyssen',libraryDirector:'Paul Thirion'},
  {id:'ulb',name:'Université libre de Bruxelles',short:'ULB',type:'university',city:'Brussels',website:'https://www.ulb.be',founded:1834,description:'A free-thinking, non-confessional French-speaking university founded in reaction to the Catholic University of Leuven, now one of the largest research universities in the French Community.',researchDirector:'Annemie Schaus',libraryDirector:'Bruno Leclercq'},
  {id:'unamur',name:'University of Namur',short:'UNamur',type:'university',city:'Namur',website:'https://www.unamur.be',founded:1831,description:'A Jesuit-founded university known for its work in computer science, mathematics and interdisciplinary research on the information society.',researchDirector:'Annick Castiaux',libraryDirector:'Marie-France Juchert'},
  {id:'umons',name:'Université de Mons',short:'UMons',type:'university',city:'Mons',website:'https://web.umons.ac.be',founded:2009,description:'Formed by the merger of the Faculté Polytechnique de Mons and the Université de Mons-Hainaut, with strength in engineering and multilingual studies.',researchDirector:'Philippe Dubois',libraryDirector:'Francesco Lo Bue'},
  {id:'uzleuven',name:'UZ Leuven (University Hospitals Leuven)',short:'UZ Leuven',type:'medical',city:'Leuven',website:'https://www.uzleuven.be',founded:1976,description:'KU Leuven\'s teaching hospital and one of Europe\'s largest academic hospitals, formed from the merger of several Leuven clinics.',researchDirector:'Paul Herijgers',libraryDirector:''},
  {id:'uzgent',name:'Ghent University Hospital',short:'UZ Gent',type:'medical',city:'Ghent',website:'https://www.uzgent.be',founded:1962,description:'Ghent University\'s teaching hospital and one of Belgium\'s largest, providing tertiary care and clinical research across nearly every specialty.',researchDirector:'Frank Vermassen',libraryDirector:''},
  {id:'uza',name:'Antwerp University Hospital',short:'UZA',type:'medical',city:'Edegem',website:'https://www.uza.be',founded:1979,description:'The University of Antwerp\'s teaching hospital, located in Edegem just outside Antwerp, with particular strength in transplant medicine.',researchDirector:'Guy Hans',libraryDirector:''},
  {id:'uzbrussel',name:'UZ Brussel',short:'UZ Brussel',type:'medical',city:'Jette',website:'https://www.uzbrussel.be',founded:1977,description:'Vrije Universiteit Brussel\'s teaching hospital in Jette, serving as the main clinical research site for VUB\'s medical faculty.',researchDirector:'Mark De Ridder',libraryDirector:''},
  {id:'chuliege',name:'CHU de Liège',short:'CHU Liège',type:'medical',city:'Liège',website:'https://www.chuliege.be',founded:1986,description:'Université de Liège\'s teaching hospital, based primarily on the Sart Tilman campus.',researchDirector:'Marc De Paoli',libraryDirector:''},
  {id:'saintluc',name:'Cliniques universitaires Saint-Luc',short:'Saint-Luc',type:'medical',city:'Woluwe-Saint-Lambert',website:'https://www.saintluc.be',founded:1976,description:'UCLouvain\'s Brussels teaching hospital, one of the largest university hospitals in the French Community.',researchDirector:'Philippe Leroy',libraryDirector:''},
  {id:'erasme',name:'Hôpital Erasme',short:'Erasme',type:'medical',city:'Anderlecht',website:'https://www.hopitalerasme.be',founded:1977,description:'Université libre de Bruxelles\' teaching hospital in Anderlecht, now part of the Hôpitaux Universitaires de Bruxelles (H.U.B) network.',researchDirector:'Renaud Witmeur',libraryDirector:''},
  {id:'bordet',name:'Institut Jules Bordet',short:'Bordet',type:'medical',city:'Brussels',website:'https://www.bordet.be',founded:1939,description:'Belgium\'s dedicated cancer research and treatment institute, affiliated with ULB and now co-located with Hôpital Erasme within H.U.B.',researchDirector:'Renaud Witmeur',libraryDirector:''},
  {id:'chunamur',name:'CHU UCL Namur (Godinne)',short:'CHU UCL Namur',type:'medical',city:'Yvoir',website:'https://www.chuuclnamur.be',founded:1975,description:'Part of the UCLouvain hospital network, serving the Namur province from its Godinne campus.',researchDirector:'Sandra Giunta',libraryDirector:''},
  {id:'imec',name:'imec',short:'imec',type:'research',city:'Leuven',website:'https://www.imec-int.com',founded:1984,description:'A world-leading independent research and innovation hub in nanoelectronics and digital technologies, closely affiliated with KU Leuven.',researchDirector:'Patrick Vandenameele',libraryDirector:''},
  {id:'vib',name:'VIB (Vlaams Instituut voor Biotechnologie)',short:'VIB',type:'research',city:'Ghent',website:'https://www.vib.be',founded:1996,description:'A Flemish life-sciences research institute operating in partnership with all five Flemish universities.',researchDirector:'Christine Durinx & Jérôme Van Biervliet',libraryDirector:''},
  {id:'flandersmake',name:'Flanders Make',short:'Flanders Make',type:'research',city:'Lommel',website:'https://www.flandersmake.be',founded:2014,description:'Flanders\' strategic research centre for the manufacturing industry, focused on vehicles, machines and factories of the future.',researchDirector:'Grisja Lobbestael',libraryDirector:''},
  {id:'sciensano',name:'Sciensano',short:'Sciensano',type:'research',city:'Brussels',website:'https://www.sciensano.be',founded:2018,description:'Belgium\'s federal institute for public health research, formed by the merger of the former scientific institute of public health (WIV-ISP) and the veterinary and agrochemical research centre (CODA-CERVA).',researchDirector:'Christian Léonard',libraryDirector:''},
  {id:'rbins',name:'Royal Belgian Institute of Natural Sciences',short:'RBINS',type:'research',city:'Brussels',website:'https://www.naturalsciences.be',founded:1846,description:'A federal natural history research institute and museum, home to major biodiversity and paleontology research collections.',researchDirector:'Michel Van Camp',libraryDirector:''},
  {id:'rmi',name:'Royal Meteorological Institute of Belgium',short:'RMI',type:'research',city:'Brussels',website:'https://www.meteo.be',founded:1913,description:'Belgium\'s federal meteorological and climate research agency.',researchDirector:'Daniel Gellens',libraryDirector:''},
  {id:'rob',name:'Royal Observatory of Belgium',short:'ROB',type:'research',city:'Brussels',website:'https://www.astro.oma.be',founded:1826,description:'Belgium\'s federal astronomical and geophysical research institute, based in Uccle.',researchDirector:'Ronald Van der Linden',libraryDirector:''},
  {id:'solvay',name:'International Solvay Institutes for Physics and Chemistry',short:'Solvay Institutes',type:'research',city:'Brussels',website:'https://www.solvayinstitutes.be',founded:1912,description:'A research institute affiliated with ULB, famous for hosting the Solvay Conferences that shaped 20th-century physics.',researchDirector:'Marc Henneaux',libraryDirector:''},
  {id:'vito',name:'VITO (Flemish Institute for Technological Research)',short:'VITO',type:'research',city:'Mol',website:'https://vito.be',founded:1991,description:'An independent applied research organisation focused on cleantech, energy, materials and sustainable chemistry.',researchDirector:'Inge Neven',libraryDirector:''},
  {id:'royalacademiesbelgium',name:'Royal Academies for Science and the Arts of Belgium',short:'RASAB',type:'research',city:'Brussels',website:'https://www.academieroyale.be',founded:1772,description:'Belgium\'s learned society and national academy, administering research prizes and international scholarly exchange across its Dutch- and French-speaking classes.',researchDirector:'',libraryDirector:''},
  {id:'bira',name:'Royal Belgian Institute for Space Aeronomy',short:'BIRA-IASB',type:'research',city:'Brussels',website:'https://www.aeronomie.be',founded:1964,description:'A federal research institute studying the physics and chemistry of the atmosphere and outer space.',researchDirector:'Ann Carine Vandaele',libraryDirector:''},
  {id:'egmont',name:'Egmont Institute (Royal Institute for International Relations)',short:'Egmont Institute',type:'research',city:'Brussels',website:'https://www.egmontinstitute.be',founded:1947,description:'An independent foreign-policy think tank based in Brussels, closely linked to Belgium\'s Ministry of Foreign Affairs.',researchDirector:'Sven Biscop',libraryDirector:''},
  {id:'bruegel',name:'Bruegel',short:'Bruegel',type:'research',city:'Brussels',website:'https://www.bruegel.org',founded:2005,description:'A Brussels-based economics think tank focused on European and global economic policy.',researchDirector:'Jeromin Zettelmeyer',libraryDirector:''},
  {id:'itinera',name:'Itinera Institute',short:'Itinera',type:'research',city:'Brussels',website:'https://www.itinerainstitute.org',founded:2006,description:'An independent Belgian public-policy think tank covering economic, social and healthcare reform.',researchDirector:'Marc De Vos & Ank De Wilde',libraryDirector:''},
  {id:'fwo',name:'Research Foundation – Flanders',short:'FWO',type:'ngo',city:'Brussels',website:'https://www.fwo.be',founded:1928,description:'Flanders\' main public research-funding body, supporting fundamental and applied research at Flemish universities.',researchDirector:'Hans Willems',libraryDirector:''},
  {id:'fnrs',name:'F.R.S.-FNRS',short:'F.R.S.-FNRS',type:'ngo',city:'Brussels',website:'https://www.frs-fnrs.be',founded:1928,description:'The French Community\'s main public research-funding body, the counterpart to FWO for Wallonia and French-speaking Brussels.',researchDirector:'Véronique Halloin',libraryDirector:''},
  {id:'kbf',name:'King Baudouin Foundation',short:'King Baudouin Fdn',type:'ngo',city:'Brussels',website:'https://www.kbs-frb.be',founded:1976,description:'One of Belgium\'s largest philanthropic foundations, funding research and social initiatives across health, poverty and civic engagement.',researchDirector:'Brieuc Van Damme',libraryDirector:''},
  {id:'kotk',name:'Kom op tegen Kanker',short:'Kom op tegen Kanker',type:'ngo',city:'Brussels',website:'https://www.komoptegenkanker.be',founded:1985,description:'A Flemish cancer-research and patient-support charity funding oncology research at Flemish universities and hospitals.',researchDirector:'David Vansteenbrugge',libraryDirector:''},
  {id:'fondationcontrelecancer',name:'Fondation contre le Cancer / Stichting tegen Kanker',short:'Fondation contre le Cancer',type:'ngo',city:'Brussels',website:'https://www.cancer.be',founded:1924,description:'A Belgian cancer research and patient-support foundation operating across both language communities.',researchDirector:'Koen Van Impe',libraryDirector:''},
  {id:'itg',name:'Institute of Tropical Medicine Antwerp',short:'ITM',type:'research',city:'Antwerp',website:'https://www.itg.be',founded:'1906',description:'Leading global institute for tropical medicine and public health research; 7,700+ Web of Science articles.',researchDirector:'',libraryDirector:''},
  {id:'sckcen',name:'SCK CEN (Belgian Nuclear Research Centre)',short:'SCK CEN',type:'research',city:'Mol',website:'https://www.sckcen.be',founded:'1952',description:'Major federal nuclear research centre; portal reports 750 profiles and over 10,000 research outputs.',researchDirector:'',libraryDirector:''},
  {id:'ilvo',name:'Flanders Research Institute for Agriculture, Fisheries and Food',short:'ILVO',type:'research',city:'Merelbeke',website:'https://ilvo.vlaanderen.be',founded:'2006',description:'Flemish government agri-food research institute with active publication output.',researchDirector:'',libraryDirector:''},
  {id:'inbo',name:'Research Institute for Nature and Forest',short:'INBO',type:'research',city:'Brussels',website:'https://www.vlaanderen.be/inbo',founded:'2006',description:'Flemish government nature and forestry research institute with an active publication programme.',researchDirector:'',libraryDirector:''},
  {id:'rma',name:'Royal Military Academy',short:'RMA',type:'research',city:'Brussels',website:'https://www.rma.ac.be',founded:'1834',description:"Federal defence academy and research institute; own portal explicitly powered by Pure, Scopus and Elsevier Fingerprint Engine.",researchDirector:'',libraryDirector:''},
  {id:'rmca',name:'Royal Museum for Central Africa',short:'AfricaMuseum',type:'research',city:'Tervuren',website:'https://www.africamuseum.be',founded:'1898',description:'Federal scientific institute (BELSPO); genuine natural and human-science research institute, not just a museum.',researchDirector:'',libraryDirector:''},
  {id:'vki',name:'Von Karman Institute for Fluid Dynamics',short:'VKI',type:'research',city:'Sint-Genesius-Rode',website:'https://www.vki.ac.be',founded:'1956',description:'International nonprofit research and postgraduate institute in fluid dynamics and aerospace; 1,400+ publications.',researchDirector:'',libraryDirector:''},
  {id:'craw',name:'Centre wallon de Recherches agronomiques',short:'CRA-W',type:'research',city:'Gembloux',website:'https://www.cra.wallonie.be',founded:'1872',description:"Sole public agronomic research centre of Wallonia (~120 scientists, 23 labs); Walloon counterpart to ILVO.",researchDirector:'',libraryDirector:''},
  {id:'saintpierre',name:'CHU Saint-Pierre',short:'Saint-Pierre',type:'medical',city:'Brussels',website:'https://www.stpierre-bru.be',founded:'1935',description:'Public university hospital (ULB/VUB-affiliated) with its own clinical and translational research units.',researchDirector:'',libraryDirector:''},
  {id:'chucharleroi',name:'CHU de Charleroi (réseau HUmani)',short:'CHU Charleroi',type:'medical',city:'Charleroi',website:'https://www.humani.be',founded:'1976',description:'Large ULB-affiliated teaching hospital with a dedicated research cell and university lab; publishes in NEJM, JACI, Radiology. Its operator ISPPC now trades as the HUmani network — chu-charleroi.be redirects through isppc.be to humani.be. There is no single directeur général: three pole-level DGs sit under the president of the Comité de Direction, who is the executive head.',researchDirector:'',libraryDirector:''},
  {id:'azdelta',name:'AZ Delta',short:'AZ Delta',type:'medical',city:'Roeselare',website:'https://www.azdelta.be',founded:'2011',description:'Large regional hospital network ranked in the 2025 Nature Index for Belgium; active in multi-site KU Leuven/UGent-linked trials.',researchDirector:'',libraryDirector:''},
];

const SEED_CONTACTS = [];

// Competitor product data — verified from official university library sources (Aug 2026)
// Renewal dates verified from public contracts and library announcements
if (!window.COMP_DATA) {
  window.COMP_DATA = {
    kuleuven: {
      scopus:'yes', scopusRenewal:'', scopusProof:'https://bib.kuleuven.be/english/vleminckxveld/collection/most-important-databases',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'no', pureRenewal:'', pureProof:'https://research.kuleuven.be/en/lirias',
      wos:'yes', wosRenewal:'', openalex:'free',
      dimensions:'unknown', converis:'unknown', symplectic:'yes',
      proofWos: 'https://bib.kuleuven.be/english/vleminckxveld/collection/most-important-databases',
      proofOpenalex: 'https://openalex.org/institutions/I99464096',
    },
    ugent: {
      scopus:'yes', scopusRenewal:'', scopusProof:'https://researchtips.ugent.be/en/tips/00001753/',
      scival:'no', scivalRenewal:'', scivalProof:'https://www.kcgg.ugent.be/advies-ondersteuning/bibliometrie/',
      pure:'no', pureRenewal:'', pureProof:'https://www.ugent.be/en/research/openscience/schol-publishing/biblio.htm',
      wos:'yes', wosRenewal:'', openalex:'free',
      dimensions:'unknown', converis:'unknown', symplectic:'unknown',
      proofWos: 'https://onderzoektips.ugent.be/en/tips/00001601/',
      proofOpenalex: 'https://openalex.org/institutions/I32597200',
    },
    uantwerpen: {
      scopus:'yes', scopusRenewal:'', scopusProof:'https://www.uantwerpen.be/en/library/search-help/resources-engineering/',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'no', pureRenewal:'', pureProof:'https://repository.uantwerpen.be/docstore/d:irua:17015',
      wos:'yes', wosRenewal:'', openalex:'free',
      dimensions:'unknown', converis:'unknown', symplectic:'unknown',
      proofWos: 'https://www.uantwerpen.be/en/library/search-help/resources-engineering/',
      proofOpenalex: 'https://openalex.org/institutions/I149213910',
    },
    vub: {
      scopus:'likely', scopusRenewal:'', scopusProof:'https://www.ittenders.com/tender-detail/purchase-elsevier-package-deal-journals-an-98400012',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'yes', pureRenewal:'', pureProof:'https://wikisites.vub.ac.be/purewiki/Main_Page',
      wos:'likely', wosRenewal:'', openalex:'free',
      dimensions:'unknown', converis:'unknown', symplectic:'unknown',
      proofWos: 'https://www.myscience.be/en/news/wire/expanded_access_to_web_of_science-2026-uantwerpen',
      proofOpenalex: 'https://openalex.org/institutions/I13469542',
    },
    uhasselt: {
      scopus:'yes', scopusRenewal:'', scopusProof:'https://www.uhasselt.be/nl/universiteitsbibliotheek/collectie/aankoop-van-e-bronnen',
      scival:'no', scivalRenewal:'', scivalProof:'https://www.uhasselt.be/nl/universiteitsbibliotheek/collectie/aankoop-van-e-bronnen',
      pure:'no', pureRenewal:'', pureProof:'https://www.uhasselt.be/en/university-library/research/documentation-document-server',
      wos:'yes', wosRenewal:'', openalex:'free',
      dimensions:'unknown', converis:'unknown', symplectic:'unknown',
      proofWos: 'https://www.uhasselt.be/nl/universiteitsbibliotheek/collectie/aankoop-van-e-bronnen',
      proofOpenalex: 'https://openalex.org/institutions/I878454856',
    },
    uclouvain: {
      scopus:'yes', scopusRenewal:'', scopusProof:'https://uclouvain.be/fr/bibliotheques/btec/generalites',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'no', pureRenewal:'', pureProof:'https://uclouvain.be/en/university-libraries/dial.pr',
      wos:'unknown', wosRenewal:'', openalex:'free',
      dimensions:'unknown', converis:'unknown', symplectic:'unknown',
      proofWos: '',
      proofOpenalex: 'https://openalex.org/institutions/I95674353',
    },
    uliege: {
      scopus:'yes', scopusRenewal:'', scopusProof:'https://orbi.uliege.be/bitstream/2268/342957/1/2026-02-15_Infolitt%20%28JN%29_Part1%20and%202_ENG.pdf',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'no', pureRenewal:'', pureProof:'https://orbi.uliege.be/page/what-is-orbi',
      wos:'unknown', wosRenewal:'', openalex:'free',
      dimensions:'unknown', converis:'unknown', symplectic:'unknown',
      proofWos: '',
      proofOpenalex: 'https://openalex.org/institutions/I157674565',
    },
    ulb: {
      scopus:'yes', scopusRenewal:'', scopusProof:'https://bib.ulb.be/fr/documents/bases-de-donnees',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'no', pureRenewal:'', pureProof:'https://bib.ulb.be/en/find-documents/di-fusion',
      wos:'unknown', wosRenewal:'', openalex:'free',
      dimensions:'unknown', converis:'unknown', symplectic:'unknown',
      proofWos: '',
      proofOpenalex: 'https://openalex.org/institutions/I132053463',
    },
    unamur: {
      scopus:'yes', scopusRenewal:'', scopusProof:'https://www.unamur.be/sites/default/files/2024-06/BUMP-rapport-activite-2022.pdf',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'yes', pureRenewal:'', pureProof:'https://unamur.be/en/research/pure',
      wos:'unknown', wosRenewal:'', openalex:'free',
      dimensions:'unknown', converis:'unknown', symplectic:'unknown',
      proofWos: '',
      proofOpenalex: 'https://openalex.org/institutions/I149768937',
    },
    umons: {
      scopus:'yes', scopusRenewal:'', scopusProof:'https://web.umons.ac.be/bibliotheques/journal/scopus/',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'no', pureRenewal:'', pureProof:'https://orbi.umons.ac.be/page/what-is-orbi?locale=fr',
      wos:'unknown', wosRenewal:'', openalex:'free',
      dimensions:'unknown', converis:'unknown', symplectic:'unknown',
      proofWos: '',
      proofOpenalex: 'https://openalex.org/institutions/I130929987',
    },
    uzbrussel: {
      scopus:'unknown', scopusRenewal:'', scopusProof:'',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'yes', pureRenewal:'', pureProof:'https://researchportal.vub.be/en/organisations/uzbrussel/',
      wos:'unknown', wosRenewal:'', openalex:'unknown',
      dimensions:'unknown', converis:'unknown', symplectic:'unknown',
      proofWos: '', proofOpenalex: '',
    },
    uzleuven: {
      scopus:'unknown', scopusRenewal:'', scopusProof:'',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'no', pureRenewal:'', pureProof:'https://www.kuleuven.be/english/research/scholcomm/lirias',
      wos:'unknown', wosRenewal:'', openalex:'unknown',
      dimensions:'unknown', converis:'unknown', symplectic:'yes',
      proofWos: '', proofOpenalex: '',
    },
    uzgent: {
      scopus:'yes', scopusRenewal:'', scopusProof:'https://www.kcgg.ugent.be/zoeken/databanken/',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'no', pureRenewal:'', pureProof:'https://onderzoeksportaal.uzgent.be/',
      wos:'yes', wosRenewal:'', openalex:'unknown',
      dimensions:'unknown', converis:'unknown', symplectic:'unknown',
      proofWos: 'https://www.kcgg.ugent.be/zoeken/databanken/', proofOpenalex: '',
    },
    uza: {
      scopus:'unknown', scopusRenewal:'', scopusProof:'',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'no', pureRenewal:'', pureProof:'https://www.uantwerpen.be/en/library/research/academic-bibliography/',
      wos:'unknown', wosRenewal:'', openalex:'unknown',
      dimensions:'unknown', converis:'unknown', symplectic:'unknown',
      proofWos: '', proofOpenalex: '',
    },
    chuliege: {
      scopus:'unknown', scopusRenewal:'', scopusProof:'',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'no', pureRenewal:'', pureProof:'https://www.chuliege.be/jcms/c2_17324758/orbi',
      wos:'unknown', wosRenewal:'', openalex:'unknown',
      dimensions:'unknown', converis:'unknown', symplectic:'unknown',
      proofWos: '', proofOpenalex: '',
    },
    saintluc: {
      scopus:'unknown', scopusRenewal:'', scopusProof:'',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'no', pureRenewal:'', pureProof:'https://sites.uclouvain.be/reso/opac_css/index.php',
      wos:'unknown', wosRenewal:'', openalex:'unknown',
      dimensions:'unknown', converis:'unknown', symplectic:'unknown',
      proofWos: '', proofOpenalex: '',
    },
    erasme: {
      scopus:'unknown', scopusRenewal:'', scopusProof:'',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'no', pureRenewal:'', pureProof:'https://difusion.ulb.ac.be/',
      wos:'unknown', wosRenewal:'', openalex:'unknown',
      dimensions:'unknown', converis:'unknown', symplectic:'unknown',
      proofWos: '', proofOpenalex: '',
    },
    bordet: {
      scopus:'unknown', scopusRenewal:'', scopusProof:'',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'no', pureRenewal:'', pureProof:'https://bib.ulb.be/fr/documents/digitheque/personalia/jules-bordet/publications',
      wos:'unknown', wosRenewal:'', openalex:'unknown',
      dimensions:'unknown', converis:'unknown', symplectic:'unknown',
      proofWos: '', proofOpenalex: '',
    },
    chunamur: {
      scopus:'unknown', scopusRenewal:'', scopusProof:'',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'unknown', pureRenewal:'', pureProof:'https://en.wikipedia.org/wiki/CHU_UCLouvain_Namur',
      wos:'unknown', wosRenewal:'', openalex:'unknown',
      dimensions:'unknown', converis:'unknown', symplectic:'unknown',
      proofWos: '', proofOpenalex: '',
    },
    imec:                  { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'no',pureRenewal:'',pureProof:'https://imec-publications.be/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    vib:                   { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'no',pureRenewal:'',pureProof:'https://biblio.ugent.be/organization/VIB', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    flandersmake:          { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'no',pureRenewal:'',pureProof:'https://www.researchportal.be/en/organisation/flandersmakekuleuven-ma', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    sciensano:             { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'no',pureRenewal:'',pureProof:'https://www.belspo.be/belspo/openscience/pub_orfeo_en.stm', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    rbins:                 { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'no',pureRenewal:'',pureProof:'https://biblio.naturalsciences.be/rbins-publications', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    rmi:                   { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'no',pureRenewal:'',pureProof:'https://orfeo.belnet.be/handle/internal/9', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    rob:                   { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'no',pureRenewal:'',pureProof:'https://orfeo.belnet.be/handle/internal/3937', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    solvay:                { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'no',pureRenewal:'',pureProof:'https://cevipol.phisoc.ulb.be/en/di-fusion', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    vito:                  { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://vito.be/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    royalacademiesbelgium: { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://researchportal.vub.be/en/activities/koninklijke-vlaamse-academie-van-belgi%C3%AB-voor-wetenschappen-en-kun-7', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    bira:                  { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'no',pureRenewal:'',pureProof:'https://www.aeronomie.be/en/publications', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    egmont:                { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'no',pureRenewal:'',pureProof:'https://researchportal.vub.be/en/activities/egmont-the-royal-institute-for-international-relations-external-o/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    bruegel:               { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.bruegel.org/publications', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    itinera:               { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.itinerainstitute.org/en/itinera-analysis/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    fwo:                   { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.fwo.be/en/about-fwo/who-is-fwo/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    fnrs:                  { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.frs-fnrs.be/en/our-commitments/open-science', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    kbf:                   { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://kbs-frb.be/en/publications-and-data', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    kotk:                  { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.komoptegenkanker.be/wat-we-doen/onderzoek-en-zorg-financieren', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    fondationcontrelecancer: { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.scientifyresearch.org/funder/fondation-contre-le-cancer-stichting-tegen-kanker/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    itg:          { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'yes',pureRenewal:'',pureProof:'https://itg.elsevierpure.com/en/organisations/malariology/', wos:'yes',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'https://lib.itg.be/databases/',proofOpenalex:'' },
    sckcen:       { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'yes',pureRenewal:'',pureProof:'https://researchportal.sckcen.be/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    ilvo:         { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'yes',pureRenewal:'',pureProof:'https://pureportal.ilvo.be/nl/organisations/instituut-voor-landbouw-visserij-en-voedingsonderzoek/publications/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    inbo:         { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'yes',pureRenewal:'',pureProof:'https://pureportal.inbo.be/en/organisations/research-institute-for-nature-and-forest/publications/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    rma:          { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'yes',pureRenewal:'',pureProof:'https://researchportal.rma.ac.be/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    rmca:         { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.africamuseum.be/en/research/discover', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    vki:          { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.nature.com/nature-index/institution-outputs/belgium/von-karman-institute-for-fluid-dynamics/524cc889140ba0e064000006', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    craw:         { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.cra.wallonie.be/fr/les-publications', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    saintpierre:  { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.stpierre-bru.be/en/a-public-university-hospital/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    chucharleroi: { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'http://www.chu-charleroi.be/le-chu/recherche-et-enseignement', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    azdelta:      { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.nature.com/nature-index/research-leaders/2025/institution/all/all/countries-Belgium', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
  };
}
